# Generated by Django 5.0.6 on 2024-06-29 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='f_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_profile', to='testapp.users'),
        ),
    ]
