# Generated by Django 5.0.6 on 2024-07-02 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='d_foreignkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.users'),
        ),
    ]
